system_messages = {
    "system_message_topic_checker": "You are a yes-or-no machine. This means that you only output 'yes' or 'no', and nothing else. You will be given an excerpt from a text, and you will determine if it includes any information about Eastern Spruce Budworms, sometimes written as just Spruce Budworm, or SBW. Only Eastern spruce budworm counts, NOT WESTERN. Say 'yes' if it includes information and 'no' if it does not.",

    "system_message_stage_0": "You are a list-maker making a comma-separated list of sources for research papers about spruce budworms. You are given an excerpt from the text and must determine where the data is coming from. Your possible list items are: Dendrochronological samples from tree cores, Dendrochronological samples from historical buildings, Pheromone traps, Aerial defoliation survey, Survey from insect laboratory, or Personal Communication with the Department of Lands and Forest representative. If the paper uses multiple sources, list each one separately, using commas as delimiters. If no information about the methods of data collection are given, simple output 'Unknown'. It is of the utmost importance that your output is a comma-separated list. Do not write headers or any additional information. Preface the information with 'Data collection method: '.",

    "system_message_stage_0b": "You are a scientist that is extracting the location of study sites from research papers about Spruce Budworm (SBW) outbreaks. You are given an excerpt from a text and must determine if the paper gives exact geographic coordinates of the study sites. You must output the geographic coordinates exactly how it is written, and nothing else. If you don't find the coordinates, output 'Unknown.' The coordinates MUST be numeric. Preface the information with 'Location: '. You must be concise because your output will be parsed as coordinates.",

    "system_message_stage_0c": "You are a classification engine that determines the format of geocoordinate data for researchers. You are given a coordinate pulled from a research paper and you must guess whether it is a bounding box, an individual coordinate in degrees/minutes/seconds, an individual point in decimal degrees, or an invalid/incomplete location (i.e. it is not a two-dimensional bounding box, a single location, or it is not numeric geocoordinates, just a place). Valid coordinates must include latitude and longitude. Your options are 'bounding box', 'degrees/minutes', 'degrees/minutes/seconds', 'decimal degrees', and 'invalid'. Your output must be one of these options and NOTHING ELSE.",

    "system_message_stage_0c_boundingbox": "You are a formatting machine that takes unformatted bounding box coordinates and puts them into a standardized format. You will put all bounding boxes into this format: degree1°N-degree2°N, degree1°W-degree2°W. Each degree may be just a degree, or a decimal degree, a coordinate in degrees/minutes/seconds, etc. Just output this data in the right format. Your output must be this format and NOTHING ELSE.",

    "system_message_stage_0c_dm": "You are a formatting machine that takes unformatted coordinates in degrees/minutes and puts them into a standardized format. You will put all bounding boxes into this format: degree1°minute1'N, degree2°minute2'W. Just output this data in the right format. Your output must be this format and NOTHING ELSE.",

    "system_message_stage_0c_dms": "You are a formatting machine that takes unformatted coordinates in degrees/minutes/seconds and puts them into a standardized format. You will put all bounding boxes into this format: degree1°minute1'second1\"N, degree2°minute2'second2\"W. Just output this data in the right format. Your output must be this format and NOTHING ELSE.",

    "system_message_stage_0c_dd": "You are a formatting machine that takes unformatted coordinates in decimal degrees and puts them into a standardized format. You will put all bounding boxes into this format: degree1.decimal1°N, degree2.decimal2°W. Just output this data in the right format. Your output must be this format and NOTHING ELSE.",

    "system_message_stage_0d": "You are a scientist that is extracting the location of study sites from research papers about Spruce Budworm (SBW) outbreaks. You are given an excerpt from a text and must determine where the study site is located. The location you output must encompass the entire study area and must be locatable on a map using the GeoPy geoservice. If the text gives exact coordinates, output those coordinates exactly and stop. Otherwise, output the location in the following format: Province/State/Municipality, Country. If the study area takes place in the northern/southern/western/eastern part or a specific lake/town/landmark in the municipality/province/state, be sure to include that info. If there is not data about the study area or you only know the country or continent it takes place in, simply print 'Unknown'. Preface the information with 'Location: '. Be concise because your output will be parsed as csv data.",

    "system_message_year_guesser": 'You are a text analysis machine that is inferring the dates from texts. Please output the year that you think it had most likely been published in. It is of the utmost importance that you only output the individual year, and nothing else. No punctuation.',

    "system_message_stage_1": "You are a scientist extracting data from research papers about Spruce Budworm (SBW) infestations and outbreaks. You are to log every instance in which the text refers to a Spruce Budworm outbreak during any years and region. You must only include the SPECIFIC ranges of years and the SPECIFIC region of the data. The region must be locatable on a map. Be as specific as possible. General locations like 'study site' or 'tree stand #3' are not relevant. Include outbreaks whose existence is uncertain. Never include research citations from the text. Only report information related to specific SBW outbreaks in specific years and locations. ALL INFORMATION MUST BE ABOUT SPRUCE BUDWORMS",

    "system_message_stage_2": "You are a computer analyzing a text for scientists on spruce budworm (SBW) outbreaks/infestations. You are to log every instance where the text mentions whether or not an outbrea/infestation occured during a specific year or range of years and at a specific geographic location.\n\nEach line must be in csv format as follows:\n\"Location\", \"Year(s)\", \"Outbreak (Always only a 'yes', 'no' or 'uncertain')\".\n\nFor each instance, output should be a new line in this format, with no headers or labels included.\n\nThe geographic location must be identifiable on a map and can be a city, county, specific lake, etc. Do not include nonspecific or nonidentifiable locations like 'study site'.\n\nIf an outbreak lasts multiple years, write the 'year' feature as 'first_year-last_year'. There MUST be a dash in between the two years. The year section must have no alphabetic characters. For example, it cannot say 'approximately *year*' or 'unknown'.\n\nIf the authors are uncertain of an outbreak's existence, the 'outbreak' column for that outbreak should be 'uncertain'. If there was a Spruce Budworm management or control operation in a region, that means that there was a Spruce Budworm outbreak there.\n\nIt is of the utmost importance that we have as many years and locations of data as possible. References to other authors and papers are irrelevant. Only log specific instances of SBW outbreaks.\n",

    "system_message_stage_3": "You are a formatting machine that takes output from ChatGPT and ensures that it is formatted correctly. Each line must be in csv format as follows:\n\"Location\", \"Year(s)\", \"Outbreak (Always only a 'yes', 'no' or 'uncertain')\".\nEach feature must be enclosed by double quotes.\nIf the outbreak lasts multiple years, list the first year, then the last year with a '-' between them (first year-last year). Only list specific years and ranges.\nIf the last feature instead says there was any amount of defoliation or tree mortality, that is also considered a 'yes' for the outbreak feature.\nIt is of the utmost importance that you print only the one piece of data, and absolutely nothing else. Do not say anything other than returning the formatted line. Do not respond like a human. I need perfect CSV text format out of ChatGPT.",

    "system_message_check_multiple_locations": "You are a yes-or-no machine. This means that you only output 'yes' or 'no', and nothing else. You are given a string and you must determine if the string represents locations from more than one state/province. Answer with 'yes' if more than one state/province is represented and 'no' if only one state/province is represented. Sometimes locations are succeeded by the province and country they inhabit, like 'lac seul area, northwestern ontario, canada', and it is still located in only one province. It is of the utmost importance that you print 'yes' or 'no' and nothing else. Do not say anything other than returning the answer. Do not respond like a human.",

    "system_message_stage_4": "You are a computer made to give scientists town names within an area. You will be given a location in North America. Your task is to give a town that belongs at that location to be used as a locality string for GEOLocate software. If the area is very remote, give the nearest town. Put it in csv format as the following: \"city, state, country\". It is of the utmost importance that you print only the one piece of data, and absolutely nothing else. You must output a city name, even if the given area is very large or very remote."
}

few_shot_examples = {
    "stage_1_few_shot_examples": [
        {"role": "user", "content": "We reconstructed the SBW outbreak history at the northern limit of the temperate forest in southern Quebec using dendrochronological material from old buildings and five old-growth stands. Nine potential outbreaks were identified (1976–1991, 1946–1959, 1915–1929, 1872–1903, 1807–1817, 1754–1765, 1706–1717, 1664–1670, and 1630–1638) with three additional uncertain outbreaks (1647–1661, 1606–1619, and 1564–1578)."},
        {"role": "assistant", "content": "-Outbreak: 1976-1991\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1946-1959\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1915-1929\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1872-1903\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1807-1817\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1754-1765\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1706-1717\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1664-1670\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1630-1638\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1647-1661 (uncertain)\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1606-1619 (uncertain)\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1564-1578 (uncertain)\n-Region: Northern limit of the temperate forest in southern Quebec"},
        {"role": "user", "content": "Earlier potential outbreaks were identified using dendro-\nchronological material from old buildings only. Three addi-\ntional and distinct growth reductions occurred between the\nbeginning of the 18th and the early 19th centuries in 1807–\n1817 (O5), 1754–1765 (O6), and 1706–1717 (O7) (Fig. 2). (Berguet 1954)"},
        {"role": "assistant", "content": "No specific instances of SBW outbreaks with geographic locations and years were mentioned in the text."},
        {"role": "user", "content": "Several points\n in the neighbourhood of Sioux Lookout and the\n eastern portion of Lac Seul show 1866 as the\n first year of suppression, indicating that the in-\n festation had its origin in this vicinity. Within\n this area, the first apparent year of suppression\n was as early as 1862 in two localities. However,\n in both these localities the white spruce trees\n sampled were very old and showed poor diameter\n growth for approximately the last 100 years, thus\nobscuring to some extent the initiation of suppres-\n sion caused by the spruce budworm (see data for\n Minnitaki Lake, Fig. 3). From this area of\n origin the infestation spread mostly westward un-\n til by 1870 and 1871 it reached points close to\n the Manitoba boundary."},
        {"role": "assistant", "content": "1. Region: Sioux Lookout and the eastern portion of Lac Seul\n  Years: 1862-1871\n"},
        {"role": "user", "content": "Spruce beetle outbreaks have been re ported in the Rocky Mountains of western North America since the late 1800s. In their classic paper, Spruce Beetle in the Rockies,  Schmid and Frye reviewed the literature that emerged from the extensive outbreaks in Colorado in the 1940s."},
        {"role": "assistant", "content": "No instances of Spruce Budworm outbreaks recorded in the text."}
    ],

  
    "stage_2_few_shot_examples": [
        {"role": "user", "content": "Specific SBW Outbreaks:\n\n1. Outbreak: O1 (1905-1930)\n-Region: Eastern Quebec, east of the St. Lawrence River\n\n2. Outbreak: O2 (1935-1965)\n  -Region: Northern reach of southern Quebec\n\n3. Outbreak: O3 (1968-1988)\n-Region: Southwestern Quebec, along a southwest-northeast transect across central southern Quebec"},
        {"role": "assistant", "content": 'Stage 2:\n"Eastern Quebec, east of the St. Lawrence River", "1905-1930", "Yes"\n"Northern reach of southern Quebec", "1935-1965", "Yes"\n"Southwestern Quebec, along a southwest-northeast transect across central southern Quebec", "1968-1988", "Yes"'},
        {"role": "user", "content": "Stage 1:\n-Outbreak: 1976-1991\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1946-1959\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1915-1929\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1872-1903\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1807-1817\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1754-1765\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1706-1717\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1664-1670\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1630-1638\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1647-1661 (uncertain)\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1606-1619 (uncertain)\n-Region: Northern limit of the temperate forest in southern Quebec\n-Outbreak: 1564-1578 (uncertain)\n-Region: Northern limit of the temperate forest in southern Quebec"},
        {"role": "assistant", "content": '"Northern limit of the temperate forest in southern Quebec", "1976-1991", "Yes"\n"Northern limit of the temperate forest in southern Quebec", "1946-1959", "Yes"\n"Northern limit of the temperate forest in southern Quebec", "1915-1929", "Yes"\n"Northern limit of the temperate forest in southern Quebec", "1872-1903", "Yes"\n"Northern limit of the temperate forest in southern Quebec", "1807-1817", "Yes"\n"Northern limit of the temperate forest in southern Quebec", "1754-1765", "Yes"\n"Northern limit of the temperate forest in southern Quebec", "1706-1717", "Yes"\n"Northern limit of the temperate forest in southern Quebec", "1664-1670", "Yes"\n"Northern limit of the temperate forest in southern Quebec", "1630-1638", "Yes"\n"Northern limit of the temperate forest in southern Quebec", "1647-1661", "Uncertain"\n"Northern limit of the temperate forest in southern Quebec", "1606-1619", "Uncertain"\n"Northern limit of the temperate forest in southern Quebec", "1564-1578", "Uncertain"'},
        {"role": "user", "content": "Specific SBW outbreaks in specific years and locations mentioned in the text are as follows:\n\n1. Outbreak in 1989: Two epicenters were identified during this outbreak.\n2. Outbreak in 1991: Four epicenters were identified during this outbreak.\n3. Outbreak in 1996: One epicenter was identified during this outbreak.\n4. Outbreak in 2006: Four epicenters were identified during this outbreak.\n5. Outbreak in 2011: One epicenter was identified during this outbreak.\n\nPlease note that the specific locations of these epicenters were not provided in the text."},
        {"role": "assistant", "content": "No specific instances of SBW outbreaks with geographic locations and years were mentioned in the text."},
        {"role": "user", "content": "-Spruce beetle outbreaks have been reported in the Rocky Mountains of western North America since the late 1800s.\n-A new wave of outbreaks has affected Rocky Mountain subalpine spruce-fir forests beginning in the mid-1980s and continuing to the present.\n-Recent spruce beetle outbreaks in Utah alone have resulted in the deaths of over 1 million spruce trees and the loss of over 90% of the large spruce component in affected stands.\n-Just over 500,000 ha of spruce forests have been affected in Colorado and Wyoming since 1996.\n-The frequency of outbreak initiation dates varied, on average, outbreaks within a given geographic area were first reported once every 19 years.\n-Four periods of broad-scale spruce beetle outbreaks occurring from 1843 to 1860, 1882 to 1889, 1931 to 1957, and 2004 to 2010 were evident in the northwestern Colorado chronology.\n-The unprecedented scale of the current outbreaks suggests that warming temperatures attributed to climate change and the region-wide susceptibility of spruce in the spruce-fir zone have had a significant impact on outbreak occurrence.\n-The occurrence of spruce beetle outbreaks and other disturbance events in Alaska and Colorado dating back to the 1700s has been determined from chronologies constructed by utilizing tree-ring release patterns, dates of spruce beetle-induced tree mortality, and years since stand establishment."},
        {"role": "assistant", "content": "No specific instances of Spruce Budworm outbreaks with geographic locations and years were mentioned in the text."}
    ],

  
    "stage_3_few_shot_examples": [
        {"role": "user", "content": "Outbreak: 1946\nRegion: New Brunswick, Canada\n\nOutbreak: Unknown\nRegion: Algoma Forest, Ontario, Canada\n\nOutbreak: 1989\nRegion: Central New Brunswick, Canada\n\nOutbreak: Unknown\nRegion: Northern New Brunswick, Canada\n\nOutbreak: Unknown\nRegion: New Brunswick, Canada and northern New England, USA"},
        {"role": "assistant", "content": '"New Brunswick, Canada", "1946", "yes"'},
        {"role": "user", "content": 'No specific outbreaks of Spruce Budworm (SBW) were mentioned in the text.\n\n\nThe text does not provide enough information to generate a CSV line.'},
        {"role":"assistant", "content": 'No specific outbreaks of Spruce Budworm (SBW) were mentioned in the text.'},
        {"role": "user", "content": '"North American boreal forests", "several years", "Yes"\n"University of Quebec at Chicoutimi, Québec, Canada", "2015", "Yes"\n"University of Quebec at Chicoutimi, Québec, Canada", "2016", "Yes"'},
        {"role": "assistant", "content": '"University of Quebec at Chicoutimi, Québec, Canada", "2015", "Yes"\n"University of Quebec at Chicoutimi, Québec, Canada", "2016", "Yes"'},
        {"role": "user", "content": "\"Sioux Lookout area, Northwestern Ontario, Canada\", \"1858-1860\", \"Uncertain\""},
        {"role": "assistant", "content": "\"Sioux Lookout area, Northwestern Ontario, Canada\", \"1858-1860\", \"Uncertain\""},
        {"role": "user", "content": "\"Sioux Lookout area, Northwestern Ontario, Canada\", \"1945 onwards\", \"Yes\""},
        {"role": "assistant", "content": "\"Sioux Lookout area, Northwestern Ontario, Canada\", \"1945-\", \"Yes\""},
        # {"role": "user", "content": "\"Lac Seul area of Northwestern Ontario, Canada\", \"Late 19th century\", \"Yes\""},
        # {"role": "assistant", "content": "No outbreaks of Spruce Budworm with specific years given in the text."}
        {"role": "user", "content": "Outbreak: 1858-1865\nRegion: Sioux Lookout area, northwestern Ontario\nOutbreak: Uncertain\nRegion: Points close to the Manitoba boundary\nOutbreak: Uncertain\nRegion: International boundary, Lake of the Woods\nOutbreak: Current infestation\nRegion: Sioux Lookout and Wabaskang Lake area, northwestern Ontario\nOutbreak: Current infestation\nRegion: Approximately 10,000 square miles in northwestern Ontario\nOutbreak: Uncertain\nRegion: Clay Lake District\nOutbreak: Uncertain\nRegion: Cedar Lake District\nOutbreak: Uncertain\nRegion: Past outbreak area, northwestern Ontario\nOutbreak: Uncertain\nRegion: Forest stands with balsam fir dominance"},
        {"role": "assistant", "content": "\"Sioux Lookout Area, Northwestern Ontario\", \"1858-1865\""},
        {"role": "user", "content": "Outbreak: 1910-unknown\nRegion: Ottawa River Valley, Quebec, Canada\n\nOutbreak: 1940-unknown\nRegion: Ottawa River Valley, Quebec, Canada\n\nOutbreak: 1967-unknown\nRegion: Ottawa River Valley, Quebec, Canada\n\nOutbreak: 1783 (uncertain)\nRegion: Ottawa River Valley, Quebec, Canada"},
        {"role": "assistant", "content": "\"Ottawa River Valley, Quebec, Canada\", \"1910\", \"yes\"\n\"Ottawa River Valley, Quebec, Canada\", \"1940\", \"yes\"\n\"Ottawa River Valley, Quebec, Canada\", \"1967\", \"yes\"\n\"Ottawa River Valley, Quebec, Canada\", \"1783\", \"uncertain\"\n"},
        {"role": "user", "content": "Chicoutimi Cathedral, Chicoutimi, Quebec, Canada, 18th century: 1710-1716, 1754-1759\nChicoutimi Cathedral, Chicoutimi, Quebec, Canada, 19th century: 1811-1813, 1835-1841, 1868-1878"},
        {"role": "assistant", "content": "\"Chicoutimi Cathedral, Chicoutimi, Quebec, Canada\", \"1710-1716\", \"yes\"\n\"Chicoutimi Cathedral, Chicoutimi, Quebec, Canada\", \"1754-1759\", \"yes\"\n\"Chicoutimi Cathedral, Chicoutimi, Quebec, Canada\", \"1811-1813\", \"yes\"\n\"Chicoutimi Cathedral, Chicoutimi, Quebec, Canada\", \"1835-1841\", \"yes\"\n\"Chicoutimi Cathedral, Chicoutimi, Quebec, Canada\", \"1868-1878\", \"yes\""}
    ],

  
    "multiple_locations_few_shot_examples": [
        {"role": "user", "content": "northern maine, usa"},
        {"role": "assistant", "content": 'no'},
        {"role": "user", "content": "chicoutimi cathedral, chicoutimi, quebec, canada"},
        {"role": "assistant", "content": 'no'},
        {"role": "user", "content": "lac seul and lake nipigon regions, northwestern ontario, canada"},
        {"role": "assistant", "content": 'no'},
        {"role": "user", "content": "manitoba, ontario, quebec, new brunswick, nova scotia, prince edward island, newfoundland, maine, minnesota"},
        {"role": "assistant", "content": 'yes'},
        {"role": "user", "content": "zone b (quebec, ontario, manitoba)"},
        {"role": "assistant", "content": 'yes'},
        {"role": "user", "content": "laurentide park, quebec"},
        {"role": "assistant", "content": 'no'},    
        {"role": "user", "content": "Saguenay and Quebec"},
        {"role": "assistant", "content": 'no'}
    ]


}

